name: Lint - [Frontend]

# Triggers the workflow on pull requests
on:
  workflow_dispatch:
  #pull_request:
  
jobs:
  run-linters:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use cached node_modules
      uses: c-hive/gha-yarn-cache@v2
      with:
        directory: .
      
    - name: Install yarn dependencies and Run ESLint
      run: |
        yarn install
        yarn run lint
