name: Todo Deployment Pipeline

on:
  # Triggers the workflow on push or pull request events but for the dev branch
  push:
    branches: [develop]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  deploy:
    

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      #- name: Use cached node_modules
        #uses: c-hive/gha-yarn-cache@v2
        #with:
        #directory: frontend
        #- name: Install yarn dependencies and build react-spa project
        #run: |
        #cd frontend
        #yarn install
 
        #- name: Copy epictetus folder to server
        #uses: Creepios/sftp-action@v1.0.1
        #with:
                #password: ${{ secrets.SSH_PASS }}
          #host: ${{ secrets.SSH_HOST }}
          #username: ${{ secrets.SSH_USER }}
          #localPath: './public/'
          #remotePath: '/var/www/zc_plugin_todo/public/'

      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          password: ${{ secrets.SSH_PASS }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          script: |
            cd /var/www/zc_plugin_todo/
            cd public
            rm -rf js
            cd /var/www/zc_plugin_todo/
            git checkout develop
            git stash
            git pull origin develop
            composer update
            cd frontend
            yarn install
            #yarn run build
            
      - name: Create app.js
        uses: appleboy/ssh-action@master
        with:
          password: ${{ secrets.SSH_PASS }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          script: |
            cd /var/www/zc_plugin_todo/public/js
            ls
